#!/usr/bin/env bash
#
# Contains any additional work that should be performed as part of codegen
#

output_file="./build/go/protos/extra.pb.go"
count=0

printf "// Code generated by extra.sh. DO NOT EDIT.\n\n" > ${output_file}
printf "package protos\n\n" >> ${output_file}

# Make is* interfaces public to make assignments easier (and less verbose)
for lowercased in `grep 'type is.\+ interface {' build/go/protos/*.pb.go | awk {'print $2'}` ; do
  uppercased="$(tr '[:lower:]' '[:upper:]' <<< ${lowercased:0:1})${lowercased:1}"

  printf "type ${uppercased} = ${lowercased}\n" >> ${output_file}
  ((count++))
done

printf "Created '${count}' type aliases\n"
